//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.0
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mommosoft.Capi.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InfoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InfoStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mommosoft.Capi.Properties.InfoStrings", typeof(InfoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request accepted ähnelt.
        /// </summary>
        internal static string INFO_0000 {
            get {
                return ResourceManager.GetString("INFO_0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NCPI not supported by current protocol, NCPI ignored ähnelt.
        /// </summary>
        internal static string INFO_0001 {
            get {
                return ResourceManager.GetString("INFO_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Flags not supported by current protocol, flags ignored ähnelt.
        /// </summary>
        internal static string INFO_0002 {
            get {
                return ResourceManager.GetString("INFO_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alert already sent by another application ähnelt.
        /// </summary>
        internal static string INFO_0003 {
            get {
                return ResourceManager.GetString("INFO_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too many applications ähnelt.
        /// </summary>
        internal static string INFO_1001 {
            get {
                return ResourceManager.GetString("INFO_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logical block size too small; must be at least 128 bytes ähnelt.
        /// </summary>
        internal static string INFO_1002 {
            get {
                return ResourceManager.GetString("INFO_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buffer exceeds 64 kbytes ähnelt.
        /// </summary>
        internal static string INFO_1003 {
            get {
                return ResourceManager.GetString("INFO_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message buffer size too small, must be at least 1024 bytes ähnelt.
        /// </summary>
        internal static string INFO_1004 {
            get {
                return ResourceManager.GetString("INFO_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. number of logical connections not supported ähnelt.
        /// </summary>
        internal static string INFO_1005 {
            get {
                return ResourceManager.GetString("INFO_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reserved ähnelt.
        /// </summary>
        internal static string INFO_1006 {
            get {
                return ResourceManager.GetString("INFO_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message could not be accepted because of an internal busy condition ähnelt.
        /// </summary>
        internal static string INFO_1007 {
            get {
                return ResourceManager.GetString("INFO_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OS resource error (e.g. no memory) ähnelt.
        /// </summary>
        internal static string INFO_1008 {
            get {
                return ResourceManager.GetString("INFO_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COMMON-ISDN-API not installed ähnelt.
        /// </summary>
        internal static string INFO_1009 {
            get {
                return ResourceManager.GetString("INFO_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller does not support external equipment ähnelt.
        /// </summary>
        internal static string INFO_100A {
            get {
                return ResourceManager.GetString("INFO_100A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller does only support external equipment ähnelt.
        /// </summary>
        internal static string INFO_100B {
            get {
                return ResourceManager.GetString("INFO_100B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illegal application number ähnelt.
        /// </summary>
        internal static string INFO_1101 {
            get {
                return ResourceManager.GetString("INFO_1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illegal command or subcommand, or message length less than 12 octets ähnelt.
        /// </summary>
        internal static string INFO_1102 {
            get {
                return ResourceManager.GetString("INFO_1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message could not be accepted because of a queue full condition. The error
        ///code does not imply that COMMON-ISDN-API cannot receive messages directed to
        ///another controller, PLCI or NCCI. ähnelt.
        /// </summary>
        internal static string INFO_1103 {
            get {
                return ResourceManager.GetString("INFO_1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queue is empty ähnelt.
        /// </summary>
        internal static string INFO_1104 {
            get {
                return ResourceManager.GetString("INFO_1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Queue overflow: a message was lost. This indicates a configuration error. The only
        ///recovery from this error is to do the CAPI_RELEASE operation. ähnelt.
        /// </summary>
        internal static string INFO_1105 {
            get {
                return ResourceManager.GetString("INFO_1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown notification parameter ähnelt.
        /// </summary>
        internal static string INFO_1106 {
            get {
                return ResourceManager.GetString("INFO_1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message could not be accepted because of an internal busy condition ähnelt.
        /// </summary>
        internal static string INFO_1107 {
            get {
                return ResourceManager.GetString("INFO_1107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OS resource error (e.g. no memory) ähnelt.
        /// </summary>
        internal static string INFO_1108 {
            get {
                return ResourceManager.GetString("INFO_1108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die COMMON-ISDN-API not installed ähnelt.
        /// </summary>
        internal static string INFO_1109 {
            get {
                return ResourceManager.GetString("INFO_1109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller does not support external equipment ähnelt.
        /// </summary>
        internal static string INFO_110A {
            get {
                return ResourceManager.GetString("INFO_110A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Controller supports only external equipment ähnelt.
        /// </summary>
        internal static string INFO_110B {
            get {
                return ResourceManager.GetString("INFO_110B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort D-channel, level 2 ähnelt.
        /// </summary>
        internal static string INFO_3306 {
            get {
                return ResourceManager.GetString("INFO_3306", resourceCulture);
            }
        }
    }
}
